---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Running apt update
      apt: update_cache=yes
    - name: Installing required packages
      apt: name={{item}} state=present
      with_items:
       - git
